language: c
compiler:
  - clang-3.8
#  - gcc
sudo: false
before_install:
  - pip install cpp-coveralls --user
  - export LD_LIBRARY_PATH=$PWD/build/dist/lib:$LD_LIBRARY_PATH
env:
  - USE_CONTEXT=ON
  # - USE_CONTEXT=OFF
  # - USE_CONTEXT=OFF USE_EMBEDTLS=ON
matrix:
  exclude:
    - compiler: gcc
      env: USE_CONTEXT=OFF
    - compiler: gcc
      env: USE_CONTEXT=OFF USE_EMBEDTLS=ON
addons:
  apt:
    sources:
      -  ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
      - george-edison55-precise-backports
    packages:
    - libssl-dev
    - cmake
    - cmake-data
    - clang-3.8
script:
  - git clone git://github.com/cose-wg/Examples Examples
  - mkdir build
  - cd build && cmake -Duse_context=$USE_CONTEXT -Dcoveralls_send=ON -Duse_embedtls=$USE_EMBEDTLS .. && make all test
  - make coveralls


